### ISSUE TITLE
GUI not finding config files

### ISSUE THREAD

**Issue by drl2** [huin/travdata#15]
When trying to run an extract through the GUI, it can't find a book.yaml file that's present in the correct location.  Windows 11, 0.4.1 release, using config.zip from the _internal directory in the install folder.

Traceback (most recent call last):
  File "travdata\filesio.py", line 364, in open_read
  File "zipfile.py", line 1563, in open
  File "zipfile.py", line 1492, in getinfo
KeyError: "There is no item named 'core_rulebook_2022\\\\book.yaml' in the archive"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "travdata\gui\extraction\runnerwin.py", line 46, in run
  File "travdata\extraction\bookextract.py", line 217, in extract_book
  File "travdata\config\__init__.py", line 90, in load_group
  File "travdata\config\__init__.py", line 244, in load_book
  File "contextlib.py", line 137, in __enter__
  File "travdata\filesio.py", line 366, in open_read
travdata.filesio.NotFoundError: core_rulebook_2022\book.yaml

Stopped.

![image](https://github.com/huin/travdata/assets/65578730/fddb307c-7999-4a86-ab0c-180e2c23dce0)

**Comment by huin** [comment]
Thanks for your report!

I have now reproduced this on my end. My bad, I should have tested the new ZIP file features on Windows before announcing 0.4.0 onwards. I'll try to look into the exact cause and fix this evening (UK time).

## Mitigation

In the meantime, you should be able to work around this specific problem by using an unzipped configuration in a folder.

1. Download https://github.com/huin/travdata/releases/download/v0.4.1/config-v0.4.1.zip
2. Extract `config-v0.4.1.zip` into a folder.
3. In the Travdata GUI use "Select config" -> "Select directory", and then choose the folder that _contains_ `config.yaml`.

This seems to work for me, where choosing a ZIP file does not.

**Comment by huin** [comment]
Filed #16 to avoid this type of thing in future.

**Comment by huin** [comment]
Reopening until I've created a release containing this fix.

**Comment by huin** [comment]
Release v0.4.2 should fix this.
