### ISSUE TITLE
Provide a GUI/WUI

### ISSUE THREAD

**Issue by huin** [huin/travdata#9]
Not everyone likes to use or has the knowledge to use the CLI. Provide a GUI or web-UI to use the key features provided by the CLI:

* CSV extraction
* tradetable

**Comment by huin** [comment]
I've drafted a GUI on the `gui` branch, and it works reasonably well. Distribution is the tricky part.

`PyInstaller` creates a Linux binary without issue. However, when run on Windows, the resulting `.exe` file fails to start.

![Screenshot 2024-04-01 080638](https://github.com/huin/travdata/assets/405741/bdd6cbde-4448-40c5-bb35-3dc3d309d8f7)

> Traceback (most recent call last):
>  File "PyInstaller\hooks\rthooks\pyi_rth_pyside6.py", line 68, in <module>
 > File "PyInstaller\hooks\rthooks\pyi_rth_pyside6.py", line 21, in _pyi_rthook
> ImportError: cannot import name 'qt' from '_pyi_rth_utils' (C:\<REDACTED>\Devel\travdata\dist\travdata\_internal\_pyi_rth_utils\__init__.pyc)

Maybe PyInstaller needs to be told explicitly to copy extra files in.


I also tried using `pyside6-distro`. This gets a bit further, but it takes about 20 minutes to build this relatively simple application. This is wildly _excessive_, and likely precludes reasonable usage of Github Actions to do a clean-room build of the application. It at least gets this far:

![Screenshot 2024-04-01 080958](https://github.com/huin/travdata/assets/405741/2cd19d22-a028-463c-9c45-50f8981c8044)

This might be a result of needing to copy in some JAR files or something that `pyside6-distro` is unaware of (which I'd told PyInstaller about one of). However, I'm not really in favour of continuing with `pyside6-distro`, as its build time is so ridiculously high.

**Comment by huin** [comment]
Works on Windows with `poetry run travdata_gui`, however:

![Screenshot 2024-04-01 111511](https://github.com/huin/travdata/assets/405741/2ea3a231-7fde-40c6-a5d6-666ce820a58f)

![Screenshot 2024-04-01 111515](https://github.com/huin/travdata/assets/405741/240cf1f6-998f-41d4-ba97-054c36b32ea4)

**Comment by huin** [comment]
Oops, found a silly mistake in how I configured PyInstaller - fixed in 419ce001f09a680a6c1e570e5449b8ed82b28eae.

GUI largely implemented in 3bd73318920aaccdc418ac612fe8b79693cc80e5.
